# Generated by Django 5.2 on 2025-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2_footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('electricity', models.FloatField(null=True)),
                ('travel', models.FloatField(null=True)),
                ('electronics_devices', models.FloatField(null=True)),
                ('food_habbit', models.CharField(max_length=50)),
                ('water', models.FloatField(null=True)),
                ('waste', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'co2_footprint',
            },
        ),
    ]
