# Generated by Django 5.2 on 2025-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_footprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2_footprint',
            name='daily_co2_emission',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='co2_footprint',
            name='yearly_co2_emission',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
